### ISSUE TITLE
Change card '10' to 'T' for consistency

### ISSUE THREAD

**Issue by jaloff** [gornanization/1k#15]
Every card beside '10' is described by only one character, so I think that we should change '10' to 'T' for consistency.

**Comment by adasq** [comment]
But it will be no longer consistent, as we have 9 also. So it will be 9 and T. It's even worse IMHO

**Comment by alan-null** [comment]
If you want my opinion I would leave it as it is, so I can see a symbol from a real card.

**Comment by adasq** [comment]
I think we agreed on it. Closing. Feel free to reopen just in case.
